export { default as DashboardPage } from './DashboardPage'
export { default as CattlePage } from './CattlePage'
export { default as InventoryPage } from './InventoryPage'
export { default as ProfilePage } from './ProfilePage'
export { default as ClinicHistoryPage } from './ClinicHistoryPage'
export { default as ProductionPage } from './ProductionPage'
export { default as CattleDetailPage } from './CattleDetailPage'
