export { default as DashboardPage } from './DashboardPage'
export { default as CattlePage } from './CattlePage'
export { default as InventoryPage } from './InventoryPage'
export { default as UsersPage } from './UsersPage'
export { default as ClinicHistoryPage } from './ClinicHistoryPage'
export { default as ProductionPage } from './ProductionPage'
